// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bguqhxvphjhchvogdiwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndXFoeHZwaGpoY2h2b2dkaXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODkyNTgsImV4cCI6MjA2NDY2NTI1OH0.WWDctzQadlnBKiEwr5C6_oXLA5tO0YZvyZj0G_7MA9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);